name: Cloudflare Pages CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Generate local.properties
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> local.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            wrangler pages deploy ./composeApp/build/dist/wasmJs/productionExecutable \
              --project-name $CF_PROJECT_NAME \
              --branch pr-${{ github.event.pull_request.number }}
          else
            wrangler pages deploy ./composeApp/build/dist/wasmJs/productionExecutable \
              --project-name $CF_PROJECT_NAME \
              --branch main
          fi
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
